apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: virtual-server-example
spec:
  host: www.example.com
  pools:
    - monitor:
        interval: 5
        send: 'GET /status HTTP/1.1\r\nHost: www.example.com \r\nConnection: Close\r\n\r\n'
        timeout: 10
        type: http
      path: /
      service: example-svc
      servicePort: 8080
  snat: /Common/snatpool
  virtualServerAddress: 192.168.1.100
  virtualServerHTTPPort: 80
  virtualServerName: example-com-vs

